
   const bake = [
      {
           "name": "Chocolate Cake",
           "price": 40.00,
           "photo": "https://lilluna.com/wp-content/uploads/2019/01/Chocolate-Cake103.jpg",
          "amount": 8,
          "description": "This delicacy is an air cake of many sheets of thin and crispy dough",
          "category": "bake",
           "manufacturer": "Roladin",
          "arriveTime": "",
          "id": 5,
      },
      {
          "name": "Cheese Cake",
          "price": 43.00,
          "photo": "https://natashaskitchen.com/wp-content/uploads/2020/05/Pefect-Cheesecake-7.jpg",
       "amount": 12,
          "description": "round cake, consisting of two protein-nut cakes and cream 'Charlotte'",
          "category": "bake",
          "manufacturer": "Roladin",
          "arriveTime": "",
          "id": 6,
      },
      {
          "name": "Corasson",
          "price": 16.00,
          "photo": "https://keyassets-p2.timeincuk.net/wp/prod/wp-content/uploads/sites/53/2013/01/Croissant.jpg",
          "amount": 100,
          "description": "delicious donuts with fruit filling",
          "category": "bake",
          "manufacturer": "Roladin",
          "arriveTime": "",
          "id": 7,
      },
      {
          "name": "Chocolate Corasson",
          "price": 17.00,
          "photo": "https://i.pinimg.com/originals/7f/9d/87/7f9d871e53e6190a1b55c003777aa4e8.jpg",
      "amount": 55,
          "description": "Chocolate Filled Croissants",
          "category": "bake",
          "manufacturer": "Roladin",
          "arriveTime": "",
          "id": 8,
      },
      {
          "name": "Termisu Cake",
          "price": 31,
          "photo": "https://www.bezvypechki.com/wp-content/uploads/2019/03/e8ccf190-5c88-4872-86fd-fb4c79ab9332.jpg",
         "amount": 43,
          "description": "Italian cake, with mascarpone cheese and Savoyardi cookies",
          "category": "bake",
          "manufacturer": "Roladin",
          "arriveTime": "",
          "id": 9,
      }
     ];
